/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityType = { 'service' : string } |
  { 'weekend' : null } |
  { 'genericActivity' : string } |
  { 'workshops' : null } |
  { 'project' : string };
export interface AttendanceModification {
  'oldRecord' : [] | [AttendanceRecord],
  'modifiedBy' : Principal,
  'modificationType' : { 'created' : null } |
    { 'deleted' : null } |
    { 'updated' : null },
  'timestamp' : Time,
  'recordId' : bigint,
  'newRecord' : [] | [AttendanceRecord],
}
export interface AttendanceRecord {
  'id' : bigint,
  'startTime' : [] | [string],
  'status' : AttendanceStatus,
  'endTime' : [] | [string],
  'date' : Time,
  'hoursWorked' : [] | [bigint],
  'notes' : [] | [string],
  'timestamp' : Time,
  'breakDuration' : [] | [bigint],
  'activity' : ActivityType,
}
export type AttendanceStatus = { 'present' : null } |
  { 'sickness' : null } |
  { 'absent' : null } |
  { 'holiday' : null } |
  { 'law104Leave' : null } |
  { 'timeBank' : null } |
  { 'remoteWork' : null };
export interface HolidayRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'endDate' : Time,
  'user' : Principal,
  'startDate' : Time,
  'reason' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface PermissionRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'endDate' : Time,
  'user' : Principal,
  'requestType' : { 'generic' : null } |
    { 'familyEmergency' : null } |
    { 'medical' : null },
  'startDate' : Time,
  'reason' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'isEmployee' : boolean,
  'name' : string,
  'position' : string,
  'holidayBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'approveHolidayRequest' : ActorMethod<[bigint], undefined>,
  'approvePermissionRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotalHours' : ActorMethod<[Time, Time], bigint>,
  'calculateTotalHoursForAllUsers' : ActorMethod<
    [Time, Time],
    Array<[Principal, bigint]>
  >,
  'deleteAttendanceRecord' : ActorMethod<[bigint], undefined>,
  'exportAttendanceRecordsAsCSV' : ActorMethod<[], string>,
  'exportHolidayRequestsAsCSV' : ActorMethod<[], string>,
  'exportPermissionRequestsAsCSV' : ActorMethod<[], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllAttendanceRecords' : ActorMethod<
    [],
    Array<[Principal, Array<AttendanceRecord>]>
  >,
  'getAllHolidayRequests' : ActorMethod<[], Array<HolidayRequest>>,
  'getAllPermissionRequests' : ActorMethod<[], Array<PermissionRequest>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAttendanceByDay' : ActorMethod<
    [Time],
    Array<[Principal, AttendanceRecord]>
  >,
  'getAttendanceByMonth' : ActorMethod<
    [Time],
    Array<[Principal, Array<AttendanceRecord>]>
  >,
  'getAttendanceByWeek' : ActorMethod<
    [Time],
    Array<[Principal, Array<AttendanceRecord>]>
  >,
  'getAttendanceModificationsByPeriod' : ActorMethod<
    [Time, Time],
    Array<AttendanceModification>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHolidayRequestsByPeriod' : ActorMethod<
    [Time, Time],
    Array<HolidayRequest>
  >,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMyAttendanceModifications' : ActorMethod<
    [],
    Array<AttendanceModification>
  >,
  'getMyAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getMyHolidayRequests' : ActorMethod<[], Array<HolidayRequest>>,
  'getMyPermissionRequests' : ActorMethod<[], Array<PermissionRequest>>,
  'getUserAttendanceModifications' : ActorMethod<
    [Principal],
    Array<AttendanceModification>
  >,
  'getUserAttendanceRecords' : ActorMethod<
    [Principal],
    Array<AttendanceRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'rejectHolidayRequest' : ActorMethod<[bigint], undefined>,
  'rejectPermissionRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitHolidayRequest' : ActorMethod<[Time, Time, string], bigint>,
  'submitPermissionRequest' : ActorMethod<
    [
      Time,
      Time,
      string,
      { 'generic' : null } |
        { 'familyEmergency' : null } |
        { 'medical' : null },
    ],
    bigint
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateAttendanceRecord' : ActorMethod<[bigint, AttendanceRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];