/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'sickness' : IDL.Null,
  'absent' : IDL.Null,
  'holiday' : IDL.Null,
  'law104Leave' : IDL.Null,
  'timeBank' : IDL.Null,
  'remoteWork' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'service' : IDL.Text,
  'weekend' : IDL.Null,
  'genericActivity' : IDL.Text,
  'workshops' : IDL.Null,
  'project' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(IDL.Text),
  'status' : AttendanceStatus,
  'endTime' : IDL.Opt(IDL.Text),
  'date' : Time,
  'hoursWorked' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'breakDuration' : IDL.Opt(IDL.Nat),
  'activity' : ActivityType,
});
export const HolidayRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'endDate' : Time,
  'user' : IDL.Principal,
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const PermissionRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'endDate' : Time,
  'user' : IDL.Principal,
  'requestType' : IDL.Variant({
    'generic' : IDL.Null,
    'familyEmergency' : IDL.Null,
    'medical' : IDL.Null,
  }),
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const AttendanceModification = IDL.Record({
  'oldRecord' : IDL.Opt(AttendanceRecord),
  'modifiedBy' : IDL.Principal,
  'modificationType' : IDL.Variant({
    'created' : IDL.Null,
    'deleted' : IDL.Null,
    'updated' : IDL.Null,
  }),
  'timestamp' : Time,
  'recordId' : IDL.Nat,
  'newRecord' : IDL.Opt(AttendanceRecord),
});
export const UserProfile = IDL.Record({
  'isEmployee' : IDL.Bool,
  'name' : IDL.Text,
  'position' : IDL.Text,
  'holidayBalance' : IDL.Nat,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  'approveHolidayRequest' : IDL.Func([IDL.Nat], [], []),
  'approvePermissionRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotalHours' : IDL.Func([Time, Time], [IDL.Int], ['query']),
  'calculateTotalHoursForAllUsers' : IDL.Func(
      [Time, Time],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
  'exportAttendanceRecordsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'exportHolidayRequestsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'exportPermissionRequestsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'generateInviteCodeWithRole' : IDL.Func([UserRole], [IDL.Text], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
      ['query'],
    ),
  'getAllHolidayRequests' : IDL.Func([], [IDL.Vec(HolidayRequest)], ['query']),
  'getAllPermissionRequests' : IDL.Func(
      [],
      [IDL.Vec(PermissionRequest)],
      ['query'],
    ),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAttendanceByDay' : IDL.Func(
      [Time],
      [IDL.Vec(IDL.Tuple(IDL.Principal, AttendanceRecord))],
      ['query'],
    ),
  'getAttendanceByMonth' : IDL.Func(
      [Time],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
      ['query'],
    ),
  'getAttendanceByWeek' : IDL.Func(
      [Time],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
      ['query'],
    ),
  'getAttendanceModificationsByPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(AttendanceModification)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHolidayRequestsByPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(HolidayRequest)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMyAttendanceModifications' : IDL.Func(
      [],
      [IDL.Vec(AttendanceModification)],
      ['query'],
    ),
  'getMyAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getMyHolidayRequests' : IDL.Func([], [IDL.Vec(HolidayRequest)], ['query']),
  'getMyPermissionRequests' : IDL.Func(
      [],
      [IDL.Vec(PermissionRequest)],
      ['query'],
    ),
  'getUserAttendanceModifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceModification)],
      ['query'],
    ),
  'getUserAttendanceRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
  'rejectHolidayRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectPermissionRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHolidayRequest' : IDL.Func([Time, Time, IDL.Text], [IDL.Nat], []),
  'submitPermissionRequest' : IDL.Func(
      [
        Time,
        Time,
        IDL.Text,
        IDL.Variant({
          'generic' : IDL.Null,
          'familyEmergency' : IDL.Null,
          'medical' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateAttendanceRecord' : IDL.Func([IDL.Nat, AttendanceRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'sickness' : IDL.Null,
    'absent' : IDL.Null,
    'holiday' : IDL.Null,
    'law104Leave' : IDL.Null,
    'timeBank' : IDL.Null,
    'remoteWork' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'service' : IDL.Text,
    'weekend' : IDL.Null,
    'genericActivity' : IDL.Text,
    'workshops' : IDL.Null,
    'project' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(IDL.Text),
    'status' : AttendanceStatus,
    'endTime' : IDL.Opt(IDL.Text),
    'date' : Time,
    'hoursWorked' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'breakDuration' : IDL.Opt(IDL.Nat),
    'activity' : ActivityType,
  });
  const HolidayRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'endDate' : Time,
    'user' : IDL.Principal,
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const PermissionRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'endDate' : Time,
    'user' : IDL.Principal,
    'requestType' : IDL.Variant({
      'generic' : IDL.Null,
      'familyEmergency' : IDL.Null,
      'medical' : IDL.Null,
    }),
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const AttendanceModification = IDL.Record({
    'oldRecord' : IDL.Opt(AttendanceRecord),
    'modifiedBy' : IDL.Principal,
    'modificationType' : IDL.Variant({
      'created' : IDL.Null,
      'deleted' : IDL.Null,
      'updated' : IDL.Null,
    }),
    'timestamp' : Time,
    'recordId' : IDL.Nat,
    'newRecord' : IDL.Opt(AttendanceRecord),
  });
  const UserProfile = IDL.Record({
    'isEmployee' : IDL.Bool,
    'name' : IDL.Text,
    'position' : IDL.Text,
    'holidayBalance' : IDL.Nat,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    'approveHolidayRequest' : IDL.Func([IDL.Nat], [], []),
    'approvePermissionRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotalHours' : IDL.Func([Time, Time], [IDL.Int], ['query']),
    'calculateTotalHoursForAllUsers' : IDL.Func(
        [Time, Time],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
    'exportAttendanceRecordsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'exportHolidayRequestsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'exportPermissionRequestsAsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'generateInviteCodeWithRole' : IDL.Func([UserRole], [IDL.Text], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
        ['query'],
      ),
    'getAllHolidayRequests' : IDL.Func(
        [],
        [IDL.Vec(HolidayRequest)],
        ['query'],
      ),
    'getAllPermissionRequests' : IDL.Func(
        [],
        [IDL.Vec(PermissionRequest)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAttendanceByDay' : IDL.Func(
        [Time],
        [IDL.Vec(IDL.Tuple(IDL.Principal, AttendanceRecord))],
        ['query'],
      ),
    'getAttendanceByMonth' : IDL.Func(
        [Time],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
        ['query'],
      ),
    'getAttendanceByWeek' : IDL.Func(
        [Time],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
        ['query'],
      ),
    'getAttendanceModificationsByPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(AttendanceModification)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHolidayRequestsByPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(HolidayRequest)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMyAttendanceModifications' : IDL.Func(
        [],
        [IDL.Vec(AttendanceModification)],
        ['query'],
      ),
    'getMyAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMyHolidayRequests' : IDL.Func([], [IDL.Vec(HolidayRequest)], ['query']),
    'getMyPermissionRequests' : IDL.Func(
        [],
        [IDL.Vec(PermissionRequest)],
        ['query'],
      ),
    'getUserAttendanceModifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceModification)],
        ['query'],
      ),
    'getUserAttendanceRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
    'rejectHolidayRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectPermissionRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHolidayRequest' : IDL.Func([Time, Time, IDL.Text], [IDL.Nat], []),
    'submitPermissionRequest' : IDL.Func(
        [
          Time,
          Time,
          IDL.Text,
          IDL.Variant({
            'generic' : IDL.Null,
            'familyEmergency' : IDL.Null,
            'medical' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateAttendanceRecord' : IDL.Func([IDL.Nat, AttendanceRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };