/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export type Time = bigint;
export interface HolidayRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    user: Principal;
    startDate: Time;
    reason: string;
}
export interface AttendanceModification {
    oldRecord?: AttendanceRecord;
    modifiedBy: Principal;
    modificationType: Variant_created_deleted_updated;
    timestamp: Time;
    recordId: bigint;
    newRecord?: AttendanceRecord;
}
export interface PermissionRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    user: Principal;
    requestType: Variant_generic_familyEmergency_medical;
    startDate: Time;
    reason: string;
}
export interface AttendanceRecord {
    id: bigint;
    startTime?: string;
    status: AttendanceStatus;
    endTime?: string;
    date: Time;
    hoursWorked?: bigint;
    notes?: string;
    timestamp: Time;
    breakDuration?: bigint;
    activity: ActivityType;
}
export type ActivityType = {
    __kind__: "service";
    service: string;
} | {
    __kind__: "weekend";
    weekend: null;
} | {
    __kind__: "genericActivity";
    genericActivity: string;
} | {
    __kind__: "workshops";
    workshops: null;
} | {
    __kind__: "project";
    project: string;
};
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface UserProfile {
    isEmployee: boolean;
    name: string;
    position: string;
    holidayBalance: bigint;
}
export enum AttendanceStatus {
    present = "present",
    sickness = "sickness",
    absent = "absent",
    holiday = "holiday",
    law104Leave = "law104Leave",
    timeBank = "timeBank",
    remoteWork = "remoteWork"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_created_deleted_updated {
    created = "created",
    deleted = "deleted",
    updated = "updated"
}
export enum Variant_generic_familyEmergency_medical {
    generic = "generic",
    familyEmergency = "familyEmergency",
    medical = "medical"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    approveHolidayRequest(requestId: bigint): Promise<void>;
    approvePermissionRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateTotalHours(startDate: Time, endDate: Time): Promise<bigint>;
    calculateTotalHoursForAllUsers(startDate: Time, endDate: Time): Promise<Array<[Principal, bigint]>>;
    deleteAttendanceRecord(recordId: bigint): Promise<void>;
    exportAttendanceRecordsAsCSV(): Promise<string>;
    exportHolidayRequestsAsCSV(): Promise<string>;
    exportPermissionRequestsAsCSV(): Promise<string>;
    generateInviteCode(): Promise<string>;
    getAllAttendanceRecords(): Promise<Array<[Principal, Array<AttendanceRecord>]>>;
    getAllHolidayRequests(): Promise<Array<HolidayRequest>>;
    getAllPermissionRequests(): Promise<Array<PermissionRequest>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAttendanceByDay(date: Time): Promise<Array<[Principal, AttendanceRecord]>>;
    getAttendanceByMonth(startDate: Time): Promise<Array<[Principal, Array<AttendanceRecord>]>>;
    getAttendanceByWeek(startDate: Time): Promise<Array<[Principal, Array<AttendanceRecord>]>>;
    getAttendanceModificationsByPeriod(startDate: Time, endDate: Time): Promise<Array<AttendanceModification>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHolidayRequestsByPeriod(startDate: Time, endDate: Time): Promise<Array<HolidayRequest>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getMyAttendanceModifications(): Promise<Array<AttendanceModification>>;
    getMyAttendanceRecords(): Promise<Array<AttendanceRecord>>;
    getMyHolidayRequests(): Promise<Array<HolidayRequest>>;
    getMyPermissionRequests(): Promise<Array<PermissionRequest>>;
    getUserAttendanceModifications(user: Principal): Promise<Array<AttendanceModification>>;
    getUserAttendanceRecords(user: Principal): Promise<Array<AttendanceRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordAttendance(record: AttendanceRecord): Promise<void>;
    rejectHolidayRequest(requestId: bigint): Promise<void>;
    rejectPermissionRequest(requestId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitHolidayRequest(startDate: Time, endDate: Time, reason: string): Promise<bigint>;
    submitPermissionRequest(startDate: Time, endDate: Time, reason: string, requestType: Variant_generic_familyEmergency_medical): Promise<bigint>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateAttendanceRecord(recordId: bigint, updatedRecord: AttendanceRecord): Promise<void>;
}
import type { ActivityType as _ActivityType, AttendanceModification as _AttendanceModification, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, HolidayRequest as _HolidayRequest, PermissionRequest as _PermissionRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveHolidayRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveHolidayRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveHolidayRequest(arg0);
            return result;
        }
    }
    async approvePermissionRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePermissionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePermissionRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateTotalHours(arg0: Time, arg1: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalHours(arg0, arg1);
            return result;
        }
    }
    async calculateTotalHoursForAllUsers(arg0: Time, arg1: Time): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalHoursForAllUsers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalHoursForAllUsers(arg0, arg1);
            return result;
        }
    }
    async deleteAttendanceRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendanceRecord(arg0);
            return result;
        }
    }
    async exportAttendanceRecordsAsCSV(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAttendanceRecordsAsCSV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAttendanceRecordsAsCSV();
            return result;
        }
    }
    async exportHolidayRequestsAsCSV(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportHolidayRequestsAsCSV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportHolidayRequestsAsCSV();
            return result;
        }
    }
    async exportPermissionRequestsAsCSV(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportPermissionRequestsAsCSV();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportPermissionRequestsAsCSV();
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllAttendanceRecords(): Promise<Array<[Principal, Array<AttendanceRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttendanceRecords();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttendanceRecords();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHolidayRequests(): Promise<Array<HolidayRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHolidayRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHolidayRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPermissionRequests(): Promise<Array<PermissionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPermissionRequests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPermissionRequests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAttendanceByDay(arg0: Time): Promise<Array<[Principal, AttendanceRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDay(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDay(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByMonth(arg0: Time): Promise<Array<[Principal, Array<AttendanceRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByMonth(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByMonth(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByWeek(arg0: Time): Promise<Array<[Principal, Array<AttendanceRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByWeek(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByWeek(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceModificationsByPeriod(arg0: Time, arg1: Time): Promise<Array<AttendanceModification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceModificationsByPeriod(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceModificationsByPeriod(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolidayRequestsByPeriod(arg0: Time, arg1: Time): Promise<Array<HolidayRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolidayRequestsByPeriod(arg0, arg1);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolidayRequestsByPeriod(arg0, arg1);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getMyAttendanceModifications(): Promise<Array<AttendanceModification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendanceModifications();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendanceModifications();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttendanceRecords(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendanceRecords();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendanceRecords();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHolidayRequests(): Promise<Array<HolidayRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHolidayRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHolidayRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPermissionRequests(): Promise<Array<PermissionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPermissionRequests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPermissionRequests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAttendanceModifications(arg0: Principal): Promise<Array<AttendanceModification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAttendanceModifications(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAttendanceModifications(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAttendanceRecords(arg0: Principal): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAttendanceRecords(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAttendanceRecords(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordAttendance(arg0: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(to_candid_AttendanceRecord_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(to_candid_AttendanceRecord_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectHolidayRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectHolidayRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectHolidayRequest(arg0);
            return result;
        }
    }
    async rejectPermissionRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPermissionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPermissionRequest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitHolidayRequest(arg0: Time, arg1: Time, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHolidayRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHolidayRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async submitPermissionRequest(arg0: Time, arg1: Time, arg2: string, arg3: Variant_generic_familyEmergency_medical): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPermissionRequest(arg0, arg1, arg2, to_candid_variant_n38(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPermissionRequest(arg0, arg1, arg2, to_candid_variant_n38(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAttendanceRecord(arg0: bigint, arg1: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendanceRecord(arg0, to_candid_AttendanceRecord_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendanceRecord(arg0, to_candid_AttendanceRecord_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceModification_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceModification): AttendanceModification {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HolidayRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HolidayRequest): HolidayRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PermissionRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PermissionRequest): PermissionRequest {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : from_candid_AttendanceRecord_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    endDate: _Time;
    user: Principal;
    startDate: _Time;
    reason: string;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    user: Principal;
    startDate: Time;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        user: value.user,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    endDate: _Time;
    user: Principal;
    requestType: {
        generic: null;
    } | {
        familyEmergency: null;
    } | {
        medical: null;
    };
    startDate: _Time;
    reason: string;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    user: Principal;
    requestType: Variant_generic_familyEmergency_medical;
    startDate: Time;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        user: value.user,
        requestType: from_candid_variant_n21(_uploadFile, _downloadFile, value.requestType),
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oldRecord: [] | [_AttendanceRecord];
    modifiedBy: Principal;
    modificationType: {
        created: null;
    } | {
        deleted: null;
    } | {
        updated: null;
    };
    timestamp: _Time;
    recordId: bigint;
    newRecord: [] | [_AttendanceRecord];
}): {
    oldRecord?: AttendanceRecord;
    modifiedBy: Principal;
    modificationType: Variant_created_deleted_updated;
    timestamp: Time;
    recordId: bigint;
    newRecord?: AttendanceRecord;
} {
    return {
        oldRecord: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.oldRecord)),
        modifiedBy: value.modifiedBy,
        modificationType: from_candid_variant_n28(_uploadFile, _downloadFile, value.modificationType),
        timestamp: value.timestamp,
        recordId: value.recordId,
        newRecord: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.newRecord))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: [] | [string];
    status: _AttendanceStatus;
    endTime: [] | [string];
    date: _Time;
    hoursWorked: [] | [bigint];
    notes: [] | [string];
    timestamp: _Time;
    breakDuration: [] | [bigint];
    activity: _ActivityType;
}): {
    id: bigint;
    startTime?: string;
    status: AttendanceStatus;
    endTime?: string;
    date: Time;
    hoursWorked?: bigint;
    notes?: string;
    timestamp: Time;
    breakDuration?: bigint;
    activity: ActivityType;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.startTime)),
        status: from_candid_AttendanceStatus_n9(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.endTime)),
        date: value.date,
        hoursWorked: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.hoursWorked)),
        notes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        breakDuration: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.breakDuration)),
        activity: from_candid_ActivityType_n12(_uploadFile, _downloadFile, value.activity)
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _AttendanceRecord]): [Principal, AttendanceRecord] {
    return [
        value[0],
        from_candid_AttendanceRecord_n6(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_AttendanceRecord>]): [Principal, Array<AttendanceRecord>] {
    return [
        value[0],
        from_candid_vec_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    sickness: null;
} | {
    absent: null;
} | {
    holiday: null;
} | {
    law104Leave: null;
} | {
    timeBank: null;
} | {
    remoteWork: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "sickness" in value ? AttendanceStatus.sickness : "absent" in value ? AttendanceStatus.absent : "holiday" in value ? AttendanceStatus.holiday : "law104Leave" in value ? AttendanceStatus.law104Leave : "timeBank" in value ? AttendanceStatus.timeBank : "remoteWork" in value ? AttendanceStatus.remoteWork : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: string;
} | {
    weekend: null;
} | {
    genericActivity: string;
} | {
    workshops: null;
} | {
    project: string;
}): {
    __kind__: "service";
    service: string;
} | {
    __kind__: "weekend";
    weekend: null;
} | {
    __kind__: "genericActivity";
    genericActivity: string;
} | {
    __kind__: "workshops";
    workshops: null;
} | {
    __kind__: "project";
    project: string;
} {
    return "service" in value ? {
        __kind__: "service",
        service: value.service
    } : "weekend" in value ? {
        __kind__: "weekend",
        weekend: value.weekend
    } : "genericActivity" in value ? {
        __kind__: "genericActivity",
        genericActivity: value.genericActivity
    } : "workshops" in value ? {
        __kind__: "workshops",
        workshops: value.workshops
    } : "project" in value ? {
        __kind__: "project",
        project: value.project
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generic: null;
} | {
    familyEmergency: null;
} | {
    medical: null;
}): Variant_generic_familyEmergency_medical {
    return "generic" in value ? Variant_generic_familyEmergency_medical.generic : "familyEmergency" in value ? Variant_generic_familyEmergency_medical.familyEmergency : "medical" in value ? Variant_generic_familyEmergency_medical.medical : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: null;
} | {
    deleted: null;
} | {
    updated: null;
}): Variant_created_deleted_updated {
    return "created" in value ? Variant_created_deleted_updated.created : "deleted" in value ? Variant_created_deleted_updated.deleted : "updated" in value ? Variant_created_deleted_updated.updated : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HolidayRequest>): Array<HolidayRequest> {
    return value.map((x)=>from_candid_HolidayRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PermissionRequest>): Array<PermissionRequest> {
    return value.map((x)=>from_candid_PermissionRequest_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _AttendanceRecord]>): Array<[Principal, AttendanceRecord]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceModification>): Array<AttendanceModification> {
    return value.map((x)=>from_candid_AttendanceModification_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_AttendanceRecord>]>): Array<[Principal, Array<AttendanceRecord>]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceRecord_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime?: string;
    status: AttendanceStatus;
    endTime?: string;
    date: Time;
    hoursWorked?: bigint;
    notes?: string;
    timestamp: Time;
    breakDuration?: bigint;
    activity: ActivityType;
}): {
    id: bigint;
    startTime: [] | [string];
    status: _AttendanceStatus;
    endTime: [] | [string];
    date: _Time;
    hoursWorked: [] | [bigint];
    notes: [] | [string];
    timestamp: _Time;
    breakDuration: [] | [bigint];
    activity: _ActivityType;
} {
    return {
        id: value.id,
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        status: to_candid_AttendanceStatus_n34(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        date: value.date,
        hoursWorked: value.hoursWorked ? candid_some(value.hoursWorked) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timestamp: value.timestamp,
        breakDuration: value.breakDuration ? candid_some(value.breakDuration) : candid_none(),
        activity: to_candid_ActivityType_n36(_uploadFile, _downloadFile, value.activity)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    sickness: null;
} | {
    absent: null;
} | {
    holiday: null;
} | {
    law104Leave: null;
} | {
    timeBank: null;
} | {
    remoteWork: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.sickness ? {
        sickness: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value == AttendanceStatus.holiday ? {
        holiday: null
    } : value == AttendanceStatus.law104Leave ? {
        law104Leave: null
    } : value == AttendanceStatus.timeBank ? {
        timeBank: null
    } : value == AttendanceStatus.remoteWork ? {
        remoteWork: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "service";
    service: string;
} | {
    __kind__: "weekend";
    weekend: null;
} | {
    __kind__: "genericActivity";
    genericActivity: string;
} | {
    __kind__: "workshops";
    workshops: null;
} | {
    __kind__: "project";
    project: string;
}): {
    service: string;
} | {
    weekend: null;
} | {
    genericActivity: string;
} | {
    workshops: null;
} | {
    project: string;
} {
    return value.__kind__ === "service" ? {
        service: value.service
    } : value.__kind__ === "weekend" ? {
        weekend: value.weekend
    } : value.__kind__ === "genericActivity" ? {
        genericActivity: value.genericActivity
    } : value.__kind__ === "workshops" ? {
        workshops: value.workshops
    } : value.__kind__ === "project" ? {
        project: value.project
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_generic_familyEmergency_medical): {
    generic: null;
} | {
    familyEmergency: null;
} | {
    medical: null;
} {
    return value == Variant_generic_familyEmergency_medical.generic ? {
        generic: null
    } : value == Variant_generic_familyEmergency_medical.familyEmergency ? {
        familyEmergency: null
    } : value == Variant_generic_familyEmergency_medical.medical ? {
        medical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
